=== annkaliza/Todo/TodoApi/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.vehicles.com/vehicles" xmlns="https://www.vehicles.com/vehicles" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="vehicles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehicle" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- <xs:element name="postalCode">postalcode is not on cars but this was to learn how to use patterns similar to regex
                <xs:simpleType>
                    <xs:restriction>
                        <xs:pattern value="[a-zA-Z][0-9][a-zA-Z][] [0-9][a-zA-Z][0-9]"></xs:pattern>this has space in btn
                        <xs:pattern value="[a-zA-Z][0-9][a-zA-Z][0-9][a-zA-Z][0-9]"></xs:pattern> has no space
                    </xs:restriction>
                </xs:simpleType>
                </xs:element > -->
                            <!-- <xs:element name="year" type="xs:int" maxOccurs="1"> -->
                            <xs:element name="year" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1920"></xs:minInclusive>
                                        <xs:maxExclusive value="2064"></xs:maxExclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <!-- <xs:element name="make" type="xs:string"> -->
                            <xs:element name="make">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Ford"></xs:enumeration>
                                        <xs:enumeration value="Toyota"></xs:enumeration>
                                        <xs:enumeration value="BMW"></xs:enumeration>
                                        <xs:enumeration value="Audi"></xs:enumeration>
                                        <xs:enumeration value="Chevrolet"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="model" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== annkaliza/Todo/TodoApi/sample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="transform.xsl" ?>
<vehicles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.vehicles.com/vehicles schema.xsd" xmlns="https://www.vehicles.com/vehicles">
    <vehicle model="Corvette">
        <year>2019</year>
        <make>Chevrolet</make>
    </vehicle>
    <vehicle model="E350">
        <year>1997</year>
        <make>Ford</make>
    </vehicle>
    <vehicle model="Rav4">
        <year>2018</year>
        <make>Toyota</make>
    </vehicle>
</vehicles>
